# Generated by Django 4.1 on 2022-08-26 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfamilia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='edad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='familia',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
    ]
